INSERT INTO "Service" (nom, description, code)
VALUES
  ('🩺 Consultation Médicale', 'Service de consultation médicale', 'CONSULT'),
  ('💉 Infirmerie', 'Service d''infirmerie', 'INFIRMERIE'),
  ('🧪 Laboratoire', 'Service de laboratoire', 'LABO'),
  ('📷 Imagerie Médicale', 'Service d''imagerie médicale', 'IMAGERIE'),
  ('💳 Caisse', 'Service de caisse', 'CAISSE'),
  ('💊 Pharmacie', 'Service de pharmacie', 'PHARMACIE'),
  ('🦷 Odontologie', 'Service de soins dentaires', 'ODONTO'),
  ('👶 Maternité', 'Service de maternité et suivi prénatal', 'MATERNITE'),
  ('🏥 Urgences', 'Service d''urgences médicales', 'URGENCES'),
  ('🧠 Neurologie', 'Service de neurologie', 'NEURO'),
  ('❤️ Cardiologie', 'Service de cardiologie', 'CARDIO'),
  ('👁️ Ophtalmologie', 'Service d''ophtalmologie', 'OPHTALMO'),
  ('🦴 Orthopédie', 'Service d''orthopédie', 'ORTHO'),
  ('🩻 Radiologie', 'Service de radiologie', 'RADIO'),
  ('🧬 Génétique', 'Service de génétique médicale', 'GENETIQUE'),
  ('🧑‍⚕️ Rééducation', 'Service de physiothérapie et rééducation', 'REEDUCATION'),
  ('🫀 Pneumologie', 'Service de pneumologie et voies respiratoires', 'PNEUMO'),
  ('🩸 Hématologie', 'Service d''hématologie', 'HEMATO'),
  ('🧪 Biochimie', 'Service de biochimie et analyses médicales', 'BIOCHIMIE'),
  ('🦠 Microbiologie', 'Service de microbiologie et infectiologie', 'MICROBIO'),
  ('🫁 Allergologie', 'Service d''allergologie et immunologie', 'ALLERGO'),
  ('🧠 Psychiatrie', 'Service de psychiatrie et santé mentale', 'PSYCHIATRIE'),
  ('🧬 Endocrinologie', 'Service d''endocrinologie et métabolisme', 'ENDO'),
  ('🧬 Gynécologie', 'Service de gynécologie et suivi féminin', 'GYNECO'),
  ('🫁 Réanimation', 'Service de soins intensifs et réanimation', 'REANIMATION'),
  ('🧑‍⚕️ Kinésithérapie', 'Service de kinésithérapie et rééducation', 'KINESIO'),
  ('🧪 Pathologie', 'Service de pathologie et analyses histologiques', 'PATHO'),
  ('🦾 Prothèses', 'Service de prothèses et appareillages', 'PROTHESE'),
  ('🧬 Nutrition', 'Service de diététique et nutrition', 'NUTRITION'),
  ('🧑‍⚕️ Ambulance', 'Service de transport médicalisé', 'AMBULANCE');
