-- AlterTable
ALTER TABLE "public"."Patient" ALTER COLUMN "allergies" DROP NOT NULL,
ALTER COLUMN "antecedents" DROP NOT NULL,
ALTER COLUMN "traitements" DROP NOT NULL,
ALTER COLUMN "dateCreation" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "statut" DROP NOT NULL,
ALTER COLUMN "service" DROP NOT NULL,
ALTER COLUMN "medecinTraitant" DROP NOT NULL,
ALTER COLUMN "derniereVisite" DROP NOT NULL;
