# Generated by Django 5.2.13 on 2026-04-18 08:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chambre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20)),
                ('type', models.CharField(choices=[('Simple', 'Simple'), ('Double', 'Double'), ('Suite', 'Suite'), ('Salle commune', 'Salle commune'), ('Réanimation', 'Réanimation')], default='Simple', max_length=50)),
                ('statut', models.CharField(choices=[('Disponible', 'Disponible'), ('Occupée', 'Occupée'), ('Maintenance', 'Maintenance')], default='Disponible', max_length=50)),
                ('nombre_lits', models.IntegerField(default=1)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chambres', to='core.organisation')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chambres', to='core.service')),
            ],
            options={
                'db_table': 'chambre',
                'unique_together': {('numero', 'organisation')},
            },
        ),
        migrations.CreateModel(
            name='ConsultationMedicale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('anamnese', models.TextField(blank=True, null=True)),
                ('diagnostic', models.TextField(blank=True, null=True)),
                ('prescription', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('En cours', 'En cours'), ('Terminée', 'Terminée')], default='En cours', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dossier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultations', to='core.dossierpatient')),
                ('medecin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultations', to='core.employe')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='core.organisation')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultations', to='core.patient')),
            ],
            options={
                'db_table': 'consultation_medicale',
            },
        ),
        migrations.CreateModel(
            name='Depense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.CharField(choices=[('Salaires', 'Salaires'), ('Équipements', 'Équipements'), ('Médicaments', 'Médicaments'), ('Maintenance', 'Maintenance'), ('Fournitures', 'Fournitures'), ('Énergie', 'Énergie'), ('Autres', 'Autres')], max_length=100)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.TextField(blank=True, null=True)),
                ('date', models.DateField()),
                ('justificatif', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depenses_creees', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depenses', to='core.organisation')),
            ],
            options={
                'db_table': 'depense',
            },
        ),
        migrations.CreateModel(
            name='ExamenImagerie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Radiographie', 'Radiographie'), ('Échographie', 'Échographie'), ('Scanner', 'Scanner'), ('IRM', 'IRM'), ('Mammographie', 'Mammographie')], max_length=100)),
                ('compte_rendu', models.TextField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('Demandé', 'Demandé'), ('En cours', 'En cours'), ('Résultats disponibles', 'Résultats disponibles'), ('Annulé', 'Annulé')], default='Demandé', max_length=50)),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('date_resultat', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('demande_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='examens_imagerie_demandes', to='core.employe')),
                ('dossier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='examens_imagerie', to='core.dossierpatient')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examens_imagerie', to='core.organisation')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='examens_imagerie', to='core.patient')),
            ],
            options={
                'db_table': 'examen_imagerie',
            },
        ),
        migrations.CreateModel(
            name='ExamenLabo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_examen', models.CharField(max_length=255)),
                ('resultats', models.TextField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('Demandé', 'Demandé'), ('En cours', 'En cours'), ('Résultats disponibles', 'Résultats disponibles'), ('Annulé', 'Annulé')], default='Demandé', max_length=50)),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('date_resultat', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('demande_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='examens_labo_demandes', to='core.employe')),
                ('dossier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='examens_labo', to='core.dossierpatient')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examens_labo', to='core.organisation')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='examens_labo', to='core.patient')),
            ],
            options={
                'db_table': 'examen_labo',
            },
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_facture', models.CharField(max_length=100, unique=True)),
                ('date_facture', models.DateTimeField(auto_now_add=True)),
                ('montant_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('statut', models.CharField(choices=[('En attente', 'En attente'), ('Validée', 'Validée'), ('Payée', 'Payée')], default='En attente', max_length=50)),
                ('methode_paiement', models.CharField(blank=True, choices=[('Espèces', 'Espèces'), ('Carte Bancaire', 'Carte Bancaire'), ('Mobile Money', 'Mobile Money'), ('Virement', 'Virement')], max_length=100, null=True)),
                ('type_assurance', models.CharField(choices=[('Aucune', 'Aucune'), ('CNSS', 'CNSS'), ('CNAMGS', 'CNAMGS'), ('Assurance Privée', 'Assurance Privée')], default='Aucune', max_length=100)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factures_creees', to=settings.AUTH_USER_MODEL)),
                ('dossier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factures', to='core.dossierpatient')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factures', to='core.organisation')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factures', to='core.patient')),
            ],
            options={
                'db_table': 'facture',
            },
        ),
        migrations.CreateModel(
            name='LigneFacture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('quantite', models.IntegerField(default=1)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('montant', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='core.facture')),
            ],
            options={
                'db_table': 'ligne_facture',
            },
        ),
        migrations.CreateModel(
            name='Lit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10)),
                ('statut', models.CharField(choices=[('Libre', 'Libre'), ('Occupé', 'Occupé'), ('Maintenance', 'Maintenance')], default='Libre', max_length=50)),
                ('chambre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lits', to='core.chambre')),
            ],
            options={
                'db_table': 'lit',
                'unique_together': {('chambre', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_entree', models.DateTimeField(auto_now_add=True)),
                ('date_sortie_prevue', models.DateField(blank=True, null=True)),
                ('date_sortie_reelle', models.DateTimeField(blank=True, null=True)),
                ('motif', models.TextField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('En cours', 'En cours'), ('Sorti', 'Sorti'), ('Transféré', 'Transféré')], default='En cours', max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dossier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admissions', to='core.dossierpatient')),
                ('medecin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admissions', to='core.employe')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admissions', to='core.organisation')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admissions', to='core.patient')),
                ('lit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admissions', to='core.lit')),
            ],
            options={
                'db_table': 'admission',
            },
        ),
        migrations.CreateModel(
            name='Medicament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('dci', models.CharField(blank=True, max_length=255, null=True)),
                ('forme', models.CharField(choices=[('Comprimé', 'Comprimé'), ('Gélule', 'Gélule'), ('Sirop', 'Sirop'), ('Injectable', 'Injectable'), ('Pommade', 'Pommade'), ('Suppositoire', 'Suppositoire'), ('Collyre', 'Collyre')], default='Comprimé', max_length=100)),
                ('stock', models.IntegerField(default=0)),
                ('seuil_alerte', models.IntegerField(default=10)),
                ('prix', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('statut', models.CharField(choices=[('Disponible', 'Disponible'), ('Rupture de stock', 'Rupture de stock'), ('En commande', 'En commande')], default='Disponible', max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicaments', to='core.organisation')),
            ],
            options={
                'db_table': 'medicament',
            },
        ),
        migrations.CreateModel(
            name='Ordonnance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('En attente', 'En attente'), ('Dispensée', 'Dispensée'), ('Annulée', 'Annulée')], default='En attente', max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('medecin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordonnances', to='core.employe')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordonnances', to='core.organisation')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordonnances', to='core.patient')),
            ],
            options={
                'db_table': 'ordonnance',
            },
        ),
        migrations.CreateModel(
            name='LigneOrdonnance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField(default=1)),
                ('posologie', models.CharField(blank=True, max_length=500, null=True)),
                ('duree', models.CharField(blank=True, max_length=100, null=True)),
                ('medicament', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.medicament')),
                ('ordonnance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='core.ordonnance')),
            ],
            options={
                'db_table': 'ligne_ordonnance',
            },
        ),
        migrations.CreateModel(
            name='DispensationMedicament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_dispensation', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispensations', to='core.organisation')),
                ('pharmacien', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispensations', to='core.employe')),
                ('ordonnance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispensations', to='core.ordonnance')),
            ],
            options={
                'db_table': 'dispensation_medicament',
            },
        ),
        migrations.CreateModel(
            name='RendezVous',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('heure', models.TimeField()),
                ('type', models.CharField(choices=[('Consultation', 'Consultation'), ('Suivi', 'Suivi'), ('Urgence', 'Urgence'), ('Contrôle', 'Contrôle'), ('Téléconsultation', 'Téléconsultation')], default='Consultation', max_length=100)),
                ('statut', models.CharField(choices=[('En attente', 'En attente'), ('Confirmé', 'Confirmé'), ('Annulé', 'Annulé'), ('Terminé', 'Terminé'), ('Urgent', 'Urgent')], default='En attente', max_length=50)),
                ('duree', models.IntegerField(default=30)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('medecin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rendez_vous', to='core.employe')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rendez_vous', to='core.organisation')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rendez_vous', to='core.patient')),
            ],
            options={
                'db_table': 'rendez_vous',
                'ordering': ['date', 'heure'],
            },
        ),
        migrations.CreateModel(
            name='SoinInfirmier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_heure', models.DateTimeField(auto_now_add=True)),
                ('tension', models.CharField(blank=True, max_length=20, null=True)),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('pouls', models.IntegerField(blank=True, null=True)),
                ('respiration', models.IntegerField(blank=True, null=True)),
                ('saturation', models.IntegerField(blank=True, null=True)),
                ('poids', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('taille', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('soins_effectues', models.JSONField(blank=True, default=list)),
                ('statut', models.CharField(choices=[('En attente', 'En attente'), ('En cours', 'En cours'), ('Terminé', 'Terminé')], default='Terminé', max_length=50)),
                ('observations', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dossier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='soins', to='core.dossierpatient')),
                ('infirmier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='soins', to='core.employe')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soins_infirmiers', to='core.organisation')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='soins', to='core.patient')),
            ],
            options={
                'db_table': 'soin_infirmier',
            },
        ),
        migrations.CreateModel(
            name='Transfert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('motif', models.TextField(blank=True, null=True)),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferts', to='core.admission')),
                ('ancien_lit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferts_depuis', to='core.lit')),
                ('nouveau_lit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferts_vers', to='core.lit')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferts', to='core.organisation')),
            ],
            options={
                'db_table': 'transfert',
            },
        ),
    ]
